# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Build ROCK

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  build-rock:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - uses: actions/upload-artifact@v4
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
