name: Build

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  build-charm-under-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
    
      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable
    
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Build charm under test
        run: charmcraft pack --verbose

      - name: Archive Charm Under Test
        uses: actions/upload-artifact@v4
        with:
          name: built-charm
          path: "*.charm"
          retention-days: 5
