name: Check libraries

on:
  workflow_call:

jobs:
  check-libraries:
    runs-on: ubuntu-22.04
    steps:
      - uses: canonical/charming-actions/check-libraries@2.3.0
        with:
        credentials: "${{ secrets.CHARMHUB_TOKEN }}"
        github-token: "${{ secrets.GITHUB_TOKEN }}"    
