# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Integration test

on:
  workflow_call:
    inputs:
      charm-file-name:
        description: Tested charm file name
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: lxd

      - name: Run integration tests
        run: tox -e integration

      - name: Archive Tested Charm
        uses: actions/upload-artifact@v4
        with:
          name: tested-charm
          path: .tox/**/${{ inputs.charm-file-name }}
          retention-days: 5

      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log

      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz
