# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Integration test

on:
  workflow_call:
    inputs:
      charm-file-name:
        description: Tested charm file name
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: latest/stable
      # - name: Setup operator environment
      #   uses: charmed-kubernetes/actions-operator@main
      #   with:
      #     juju-channel: 3.4/stable
      #     provider: microk8s
      #     channel: 1.27-strict/stable
      #     microk8s-addons: "hostpath-storage dns metallb:10.0.0.2-10.0.0.10"
      # - name: Enable Multus addon
      #   continue-on-error: true
      #   run: |
      #     sudo microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus
      #     sudo microk8s enable multus
      #     sudo microk8s kubectl -n kube-system rollout status daemonset/kube-multus-ds
      #     sudo microk8s kubectl auth can-i create network-attachment-definitions
      # - name: Run integration tests
      #   run: tox -e integration
      - name: Install Charmcraft Snap
        run: sudo snap install charmcraft --classic
      - name: Build Charm
        run: charmcraft pack
      - name: Archive Tested Charm
        uses: actions/upload-artifact@v4
        with:
          name: tested-charm
          path: ./${{ inputs.charm-file-name }}
          retention-days: 5
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz
