# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: publish-charm

on:
  workflow_call:
    inputs:
      charm-file-name:
        description: Charm file name
        required: true
        type: string
      track-name:
        default: latest
        description: Name of the charmhub track to publish
        type: string
      branch-name:
        default:
        description: An additional branch name to add to the track
        type: string
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  sanitize-branch-name:
    runs-on: ubuntu-22.04
    steps:
      - name: Sanitize the branch variable
        id: sanitize
        run: |
          echo "BRANCH_NAME=/${{ inputs.branch-name }} | sed 's/\//-/2g'" >> $GITHUB_OUTPUT
        if: ${{inputs.branch-name}} != ""

  publish-charm:
    runs-on: ubuntu-22.04
    needs: [sanitize-branch-name]
    env:
      BRANCH_NAME: "${{ needs.sanitize-branch.otuputs.BRANCH_NAME}}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Fetch Tested Charm
        uses: actions/download-artifact@v4
        with:
          name: tested-charm
      - name: Move charm in current directory
        run: find ./ -name ${{ inputs.charm-file-name }} -exec mv -t ./ {} \;
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@bc8d4ee58ddf99c6f13fc80e8a14dfe1e68a8ea6
        with:
          built-charm-path: ${{ inputs.charm-file-name }}
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: ${{ inputs.track-name }}/edge${{ env.BRANCH_NAME }}
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
