# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Publish ROCK

on:
  workflow_call:

jobs:

  publish-rock:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install skopeo from rockcraft
        run: |
          sudo snap install --edge --classic rockcraft
      - uses: actions/download-artifact@v5
        with:
          name: rock

      - name: Import and push to github package
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/canonical/${image_name}:${version}"
          docker push ghcr.io/canonical/${image_name}:${version}
