name: Publish Library

on:
  workflow_call:
    inputs:
      lib-name:
        description: Lib name
        required: true
        type: string
    secrets:
      CHARMCRAFT_AUTH:
        required: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    name: Charmhub upload SD-Core lib
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Publish lib
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          set -eux
          echo "Publishing lib"
          charmcraft publish-lib ${{ inputs.lib-name }}
