# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Scan

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}

jobs:

  scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: Install skopeo from rockcraft
        run: |
          sudo snap install --edge --classic rockcraft

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@v4
        with:
          name: rock

      - name: Import
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          echo "image_name=${image_name}" >> $GITHUB_ENV
          version="$(yq '.version' rockcraft.yaml)"
          echo "version=${version}" >> $GITHUB_ENV
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/canonical/${image_name}:${version}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/canonical/${{env.image_name}}:${{env.version}}"
          format: 'sarif'
          output: 'trivy-results.sarif'
          arguments: '--ignore-unfixed=false'

      - name: Download CISA KEV Catalog
        run: |
          wget https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json -O known_exploited_vulnerabilities.json

      - name: Compare found CVEs with KEVs
        run: |
          set -euo pipefail
          
          # Define the error_exit function
          error_exit() {
            echo "::error file=${BASH_SOURCE[1]},line=$1::Error: $2"
            exit 1
          }
          
          # Trap errors and call error_exit on termination
          trap 'error_exit ${LINENO} "An error occurred while comparing CVEs with KEVs."' ERR
          
          if [[ ! -s trivy-results.sarif ]]; then
            echo "Error: trivy-results.sarif file is missing or empty."
            exit 1
          fi
          
          if ! jq empty known_exploited_vulnerabilities.json >/dev/null 2>&1; then
            echo "Error: known_exploited_vulnerabilities.json is not valid JSON."
            exit 1
          fi
          
          # Get the CVEs from Trivy results
          current_cves=$(jq -r '.. | .results? | arrays | .[].ruleId' trivy-results.sarif)
          
          # Extract the list of KEV CVEs from the catalog
          kevs=$(jq -r '.vulnerabilities[] | .cveID' known_exploited_vulnerabilities.json 2>/dev/null || echo "")
          
          # If no KEV CVEs are found, log a message and continue gracefully
          if [[ -z "$kevs" ]]; then
            echo "No KEV CVEs found in the known_exploited_vulnerabilities.json catalog."
          fi
          
          # If both current_cves and kevs are empty, skip processing
          if [[ -z "$current_cves" && -z "$kevs" ]]; then
            echo "No CVEs or KEV CVEs to process. Exiting."
            exit 0
          fi
          
          # Compare CVEs and save the matched results
          comm -12 <(sort <<< "$current_cves") <(sort <<< "$kevs") > matched_cvs.txt || {
            echo "Error: Failed to compare CVEs."
            exit 1
          }
          
          # If matched_cvs.txt is empty, log a message and exit successfully
          if [[ ! -s matched_cvs.txt ]]; then
            echo "No matches found between current CVEs and the KEV catalog."
            exit 0
          fi
          
          # Create a SARIF template for the KEV matches
          matched_sarif=$(cat <<EOF
          {
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "KEV Matcher",
                    "informationUri": "https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
                    "rules": []
                  }
                },
                "results": []
              }
            ]
          }
          EOF
          )
          
          # Add matched KEVs to the SARIF file
          while read -r cve; do
            matched_sarif=$(jq \
              --arg cve "$cve" \
              '.runs[0].tool.driver.rules += [{"id": $cve, "name": $cve, "shortDescription": {"text": "CVE matched with KEV"}, "tags": ["KEV"]}] |
              .runs[0].results += [{"ruleId": $cve, "message": {"text": "This CVE matches the CISA KEV catalog.", "tags": ["KEV"]}}]' \
              <<< "$matched_sarif") || {
              echo "Error: jq failed while processing CVE $cve."
              exit 1
            }
          done < matched_cvs.txt
          
          # Save final SARIF file
          echo "$matched_sarif" > kev_matches.sarif || {
            echo "Error: Failed to save SARIF file."
            exit 1
          }  

      - name: Upload CVE results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Check if kev_matches.sarif file exists
        id: check_kev_sarif_file
        run: |
          if [ -e kev_matches.sarif ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload KEV results to GitHub Security tab
        if: ${{ steps.check_kev_sarif_file.outputs.exists == 'true' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'kev_matches.sarif'
