# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Static analysis

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  static-analysis:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: Install uv
        run: sudo snap install --classic astral-uv

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run tests using tox
        run: tox -e static
