name: TICS

on:
  workflow_call:
    inputs:
      project:
        description: 'The name of the TiCS project to submit the analysis to'
        required: true
        type: string
      dir:
        description: 'The directory where the code and tox.ini is located, if not the root of the repository'
        required: false
        default: '.'
        type: string
    secrets:
      TICSAUTHTOKEN:
        required: true

jobs:
  analyze:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3.10-venv pipx

      - name: Install tox using pipx
        run: |
          pipx install tox
          pipx inject tox tox-uv

      - name: Run tox tests to create coverage.xml
        working-directory: ${{ inputs.dir }}
        run: tox run -e unit

      - name: move results to necessary folder for TICS
        run: |
          mkdir ${{ inputs.dir }}/cover
          mv ${{ inputs.dir }}/coverage.xml ${{ inputs.dir }}/cover/coverage.xml

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: ${{ inputs.project}}
          branchdir: ${{ github.workspace }}/${{ inputs.dir }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
